spring.application.name=sistema-denuncia-bullying

sida.seguranca.crypto-key=${CRYPTO-KEY}
sida.seguranca.crypto-salt=${CRYPTO-SALT}
sida.seguranca.crypto-hmac=${CRYPTO-HMAC}

sida.seguranca.jwt.secret=${JWT-SECRET}
sida.seguranca.jwt.expiration=${JWT-EXPIRATION}
sida.seguranca.jwt.denuncia.expiration=${JWT-DENUNCIA-EXPIRATION}

spring.datasource.url=${DATABASE_URL}
spring.datasource.username= ${DATABASE_USERNAME}
spring.datasource.password= ${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect