package br.com.pr.sida.auditoria.enums;

public enum AcaoEnum {
    ACESSOU_DETALHES_DENUNCIA,
    ACESSOU_DENUNCIAS_DE_UMA_ESCOLA,
    ACESSOU_DENUNCIAS_DE_UMA_ENTIDADE,
    ENVIAR_MENSAGEM_DENUNCIA_RESPONSAVEL,
    ATUALIZAR_STATUS_DENUNCIA,
}
